name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS
    runs-on: macos-13
    strategy:
      matrix:
        swift-syntax-version: ['509.0.0..<510.0.0', '510.0.0..<511.0.0']

    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Set SWIFT_SYNTAX_VERSION environment variable
        run: echo "SWIFT_SYNTAX_VERSION=${{ matrix.swift-syntax-version }}" >> $GITHUB_ENV
      - name: Resolve Dependencies
        run: swift package resolve
      - name: Run tests
        run: swift test

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test

  # NB: 5.9 snapshot unavailable, wait for release
  # wasm:
  #   name: Wasm
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - { toolchain: wasm-5.9-RELEASE }
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: echo "${{ matrix.toolchain }}" > .swift-version
  #     - uses: swiftwasm/swiftwasm-action@v5.9
  #       with:
  #         shell-action: carton test --environment node

  # NB: 5.9 snapshot outdated, wait for release
  # windows:
  #   name: Windows
  #   runs-on: windows-latest
  #   steps:
  #     - uses: compnerd/gha-setup-swift@main
  #       with:
  #         branch: swift-5.9-release
  #         tag: 5.9-DEVELOPMENT-SNAPSHOT-2023-09-16-a
  #     - uses: actions/checkout@v4
  #     - name: Run tests
  #       run: swift test
